import Head from 'next/head';
import Aside from './Aside';
import Header from './Header';

const Layout = ({children, title}) => {
  return (
    <div className="app">
      <Head>
        <title>{`${title} - Boilerplate`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/1fd8cfbcce.js" crossOrigin="anonymous"></script>
      </Head>
      <Header />
      <Aside />
      <main role="main">
        {children}
      </main>
    </div>
  )
}

export default Layout
